# Archivo: docker-compose.yaml
# Version: 2.0 - PRODUCTION READY
# Descripción: Versión final y estable con healthchecks restaurados.

version: '3.8'

services:
  n8n_app:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_service
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      pg_database:
        condition: service_healthy # Vuelve a esperar a que esté saludable

  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_service
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      redis_cache: {}
      pg_database:
        condition: service_healthy # Vuelve a esperar a que esté saludable

  pg_database:
    image: postgres:16-alpine
    container_name: shared_postgres_db
    restart: always
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck: # Healthcheck restaurado
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis_cache:
    image: redis:7-alpine
    container_name: shared_redis_cache
    restart: always
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - evolution_redis:/data

volumes:
  n8n_data:
  evolution_instances:
  postgres_data:
  evolution_redis:
