# Archivo: docker-compose.yaml
# Version: 1.7 - DEBUGGING
# Descripción: Versión para depuración SIN healthcheck en la base de datos.
# Esto nos permitirá ver el error real de inicialización.

version: '3.8'

services:
  n8n_app:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_service
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      pg_database:
        condition: service_started # CAMBIO: Espera a que inicie, no a que esté saludable.

  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_service
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - redis_cache
      - pg_database

  pg_database:
    image: postgres:16-alpine
    container_name: shared_postgres_db
    restart: always
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    # LA SECCIÓN healthcheck HA SIDO ELIMINADA DE AQUÍ PARA DEPURAR

  redis_cache:
    image: redis:7-alpine
    container_name: shared_redis_cache
    restart: always
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - evolution_redis:/data

volumes:
  n8n_data:
  evolution_instances:
  postgres_data:
  evolution_redis:
