# Archivo: docker-compose.yml (Versión Final Corregida)

version: '3.8'

services:
  #--- N8N SERVICE ---#
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_service
    restart: always
    environment:
      # ... (tus variables de n8n están aquí, no se tocan)
    # LA SECCIÓN 'ports' HA SIDO ELIMINADA DE AQUÍ
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      # ... (sin cambios)

  #--- EVOLUTION API SERVICE ---#
  api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_service
    restart: always
    environment:
      # ... (tus variables de api están aquí, no se tocan)
    # LA SECCIÓN 'ports' HA SIDO ELIMINADA DE AQUÍ
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - redis
      - postgres

  # ... (El resto de los servicios 'postgres' y 'redis' no cambian)
  postgres:
    image: postgres:16-alpine
    # ... (sin cambios)
  
  redis:
    image: redis:7-alpine
    # ... (sin cambios)

volumes:
  n8n_data:
    driver: local
  evolution_instances:
    driver: local
  postgres_data:
    driver: local
  evolution_redis:
    driver: local
