# Archivo: docker-compose.yml (con servicios renombrados)

version: '3.8'

services:
  #--- N8N SERVICE ---#
  n8n_app:  ## CAMBIO ##
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_service
    restart: always
    environment:
      # ...
      - DB_POSTGRESDB_HOST=pg_database  ## CAMBIO ## (Apuntando al nuevo nombre de la DB)
      # ...
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      pg_database:  ## CAMBIO ##
        condition: service_healthy
    healthcheck:
      # ... (sin cambios)

  #--- EVOLUTION API SERVICE ---#
  evolution_api:  ## CAMBIO ##
    image: atendai/evolution-api:latest
    container_name: evolution_api_service
    restart: always
    environment:
      # ...
      - DB_POSTGRESDB_HOST=pg_database  ## CAMBIO ##
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg_database:5432/${EVOLUTION_DB_NAME}  ## CAMBIO ##
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg_database:5432/${EVOLUTION_DB_NAME}  ## CAMBIO ##
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg_database:5432/${EVOLUTION_DB_NAME}  ## CAMBIO ##
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis_cache:6379/6  ## CAMBIO ## (Apuntando al nuevo nombre de Redis)
      # ...
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - redis_cache  ## CAMBIO ##
      - pg_database  ## CAMBIO ##

  #--- SHARED POSTGRESQL DATABASE ---#
  pg_database:  ## CAMBIO ##
    image: postgres:16-alpine
    container_name: shared_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${N8N_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      # ... (sin cambios)

  #--- SHARED REDIS CACHE ---#
  redis_cache:  ## CAMBIO ##
    image: redis:7-alpine
    container_name: shared_redis_cache
    restart: always
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - evolution_redis:/data

#--- VOLUMES DEFINITION ---#
volumes:
  n8n_data:
    driver: local
  evolution_instances:
    driver: local
  postgres_data:
    driver: local
  evolution_redis:
    driver: local
